obj-m = rdb.o


ccflags-y := -Wno-strict-prototypes -DKM -DUSE_128_BIT_TYPES


TARGET  := rdb
WARN    := -W -Wall -Wno-strict-prototypes
	
${TARGET}.o: ../src/${TARGET}.c

.PHONY: clean

clean:
	rm -rf ${TARGET}.o
